# coding: utf-8

"""
    Modelmetry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from modelmetry.openapi.models.google_dlppii_detector_v1_config import GoogleDLPPIIDetectorV1Config

class TestGoogleDLPPIIDetectorV1Config(unittest.TestCase):
    """GoogleDLPPIIDetectorV1Config unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GoogleDLPPIIDetectorV1Config:
        """Test GoogleDLPPIIDetectorV1Config
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GoogleDLPPIIDetectorV1Config`
        """
        model = GoogleDLPPIIDetectorV1Config()
        if include_optional:
            return GoogleDLPPIIDetectorV1Config(
                info_types = [
                    ''
                    ],
                minimum_likelihood = 'LIKELY'
            )
        else:
            return GoogleDLPPIIDetectorV1Config(
                info_types = [
                    ''
                    ],
                minimum_likelihood = 'LIKELY',
        )
        """

    def testGoogleDLPPIIDetectorV1Config(self):
        """Test GoogleDLPPIIDetectorV1Config"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
