# coding: utf-8

"""
    Modelmetry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from modelmetry.openapi.models.guardrail_check import GuardrailCheck

class TestGuardrailCheck(unittest.TestCase):
    """GuardrailCheck unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GuardrailCheck:
        """Test GuardrailCheck
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GuardrailCheck`
        """
        model = GuardrailCheck()
        if include_optional:
            return GuardrailCheck(
                var_schema = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_by = '',
                duration_ms = 56,
                guardrail_id = '',
                id = '',
                metadata = None,
                outcome = 'pass',
                payload = modelmetry.openapi.models.payload.Payload(
                    input = modelmetry.openapi.models.completion_family_data_input.CompletionFamilyData_Input(), 
                    options = {
                        'key' : null
                        }, 
                    output = modelmetry.openapi.models.output.Output(
                        messages = [
                            modelmetry.openapi.models.chat_input_messages_inner.ChatInput_Messages_inner()
                            ], 
                        text = '', ), ),
                summarised_entries = [
                    modelmetry.openapi.models.summarised_entry.SummarisedEntry(
                        check_id = '', 
                        duration_ms = 56, 
                        evaluator_id = '', 
                        findings = [
                            {
                                'key' : null
                                }
                            ], 
                        id = '', 
                        instance_id = '', 
                        message = '', 
                        outcome = '', 
                        score = 1.337, 
                        skip = '', 
                        span_id = '', 
                        tenant_id = '', 
                        trace_id = '', )
                    ],
                tenant_id = '',
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_by = ''
            )
        else:
            return GuardrailCheck(
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_by = '',
                duration_ms = 56,
                guardrail_id = '',
                id = '',
                metadata = None,
                outcome = 'pass',
                payload = modelmetry.openapi.models.payload.Payload(
                    input = modelmetry.openapi.models.completion_family_data_input.CompletionFamilyData_Input(), 
                    options = {
                        'key' : null
                        }, 
                    output = modelmetry.openapi.models.output.Output(
                        messages = [
                            modelmetry.openapi.models.chat_input_messages_inner.ChatInput_Messages_inner()
                            ], 
                        text = '', ), ),
                summarised_entries = [
                    modelmetry.openapi.models.summarised_entry.SummarisedEntry(
                        check_id = '', 
                        duration_ms = 56, 
                        evaluator_id = '', 
                        findings = [
                            {
                                'key' : null
                                }
                            ], 
                        id = '', 
                        instance_id = '', 
                        message = '', 
                        outcome = '', 
                        score = 1.337, 
                        skip = '', 
                        span_id = '', 
                        tenant_id = '', 
                        trace_id = '', )
                    ],
                tenant_id = '',
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_by = '',
        )
        """

    def testGuardrailCheck(self):
        """Test GuardrailCheck"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
