# coding: utf-8

"""
    Modelmetry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from modelmetry.openapi.models.create_event_params import CreateEventParams

class TestCreateEventParams(unittest.TestCase):
    """CreateEventParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateEventParams:
        """Test CreateEventParams
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateEventParams`
        """
        model = CreateEventParams()
        if include_optional:
            return CreateEventParams(
                at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                attributes = None,
                entry_id = '',
                name = '',
                span_id = '',
                trace_id = '',
                xid = ''
            )
        else:
            return CreateEventParams(
                name = '',
                xid = '',
        )
        """

    def testCreateEventParams(self):
        """Test CreateEventParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
