# coding: utf-8

"""
    Modelmetry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from modelmetry.openapi.models.summarised_entry import SummarisedEntry

class TestSummarisedEntry(unittest.TestCase):
    """SummarisedEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SummarisedEntry:
        """Test SummarisedEntry
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SummarisedEntry`
        """
        model = SummarisedEntry()
        if include_optional:
            return SummarisedEntry(
                check_id = '',
                duration_ms = 56,
                evaluator_id = '',
                findings = [
                    {
                        'key' : null
                        }
                    ],
                id = '',
                instance_id = '',
                message = '',
                outcome = 'na',
                skip = '',
                span_id = '',
                tenant_id = '',
                trace_id = ''
            )
        else:
            return SummarisedEntry(
                check_id = '',
                duration_ms = 56,
                evaluator_id = '',
                findings = [
                    {
                        'key' : null
                        }
                    ],
                id = '',
                instance_id = '',
                message = '',
                outcome = 'na',
                skip = '',
                span_id = '',
                tenant_id = '',
                trace_id = '',
        )
        """

    def testSummarisedEntry(self):
        """Test SummarisedEntry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
