# coding: utf-8

"""
    Modelmetry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from modelmetry.openapi.models.retrieval_payload import RetrievalPayload

class TestRetrievalPayload(unittest.TestCase):
    """RetrievalPayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RetrievalPayload:
        """Test RetrievalPayload
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RetrievalPayload`
        """
        model = RetrievalPayload()
        if include_optional:
            return RetrievalPayload(
                queries = [
                    modelmetry.openapi.models.retrieval_query.RetrievalQuery(
                        embeddings = [
                            1.337
                            ], 
                        name = '', )
                    ],
                retrieved = [
                    {
                        'key' : null
                        }
                    ]
            )
        else:
            return RetrievalPayload(
                queries = [
                    modelmetry.openapi.models.retrieval_query.RetrievalQuery(
                        embeddings = [
                            1.337
                            ], 
                        name = '', )
                    ],
                retrieved = [
                    {
                        'key' : null
                        }
                    ],
        )
        """

    def testRetrievalPayload(self):
        """Test RetrievalPayload"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
