# coding: utf-8

"""
    Modelmetry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from modelmetry.openapi.models.modelmetry_embeddings_similarity_v1_config import ModelmetryEmbeddingsSimilarityV1Config

class TestModelmetryEmbeddingsSimilarityV1Config(unittest.TestCase):
    """ModelmetryEmbeddingsSimilarityV1Config unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelmetryEmbeddingsSimilarityV1Config:
        """Test ModelmetryEmbeddingsSimilarityV1Config
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelmetryEmbeddingsSimilarityV1Config`
        """
        model = ModelmetryEmbeddingsSimilarityV1Config()
        if include_optional:
            return ModelmetryEmbeddingsSimilarityV1Config(
                extraction_method = 'last-user-vs-assistant',
                model = 'openai/text-embedding-3-small',
                reference_text = '',
                strategy = 'cosine'
            )
        else:
            return ModelmetryEmbeddingsSimilarityV1Config(
                extraction_method = 'last-user-vs-assistant',
                model = 'openai/text-embedding-3-small',
                reference_text = '',
                strategy = 'cosine',
        )
        """

    def testModelmetryEmbeddingsSimilarityV1Config(self):
        """Test ModelmetryEmbeddingsSimilarityV1Config"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
