# coding: utf-8

"""
    Modelmetry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from modelmetry.openapi.models.call import Call

class TestCall(unittest.TestCase):
    """Call unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Call:
        """Test Call
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Call`
        """
        model = Call()
        if include_optional:
            return Call(
                var_schema = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_by = '',
                duration_ms = 56,
                guardrail_id = '',
                id = '',
                metadata = None,
                outcome = 'pass',
                payload = modelmetry.openapi.models.payload.Payload(
                    input = modelmetry.openapi.models.input.Input(
                        chat = modelmetry.openapi.models.chat_input.ChatInput(
                            messages = [
                                modelmetry.openapi.models.simple_message.SimpleMessage(
                                    contents = [
                                        modelmetry.openapi.models.simple_part.SimplePart(
                                            detail = 'auto', 
                                            mime_type = '', 
                                            text = '', 
                                            uri = '', )
                                        ], 
                                    name = '', 
                                    role = 'system', 
                                    tool_call_id = '', 
                                    tool_calls = [
                                        modelmetry.openapi.models.tool_call.ToolCall(
                                            function = modelmetry.openapi.models.function.Function(
                                                arguments = null, 
                                                name = '', ), 
                                            id = '', 
                                            type = 'function', )
                                        ], )
                                ], 
                            settings = modelmetry.openapi.models.simple_options.SimpleOptions(
                                frequency_penalty = 1.337, 
                                logprobs = True, 
                                max_tokens = 56, 
                                n = 56, 
                                presence_penalty = 1.337, 
                                seed = 56, 
                                stream = True, 
                                temperature = 0, 
                                timeout = 0, 
                                tool_choice = '', 
                                tools = [
                                    modelmetry.openapi.models.tool.Tool(
                                        description = '', 
                                        name = '', 
                                        parameters = null, )
                                    ], 
                                top_logprobs = 56, 
                                top_p = 0, 
                                user = '', ), ), 
                        text = modelmetry.openapi.models.text_input.TextInput(
                            text = '', ), ), 
                    output = modelmetry.openapi.models.output.Output(), ),
                summarised_entries = [
                    modelmetry.openapi.models.summarised_entry.SummarisedEntry(
                        duration_ms = 56, 
                        evaluator_id = '', 
                        id = '', 
                        instance_id = '', 
                        message = '', 
                        metrics = [
                            modelmetry.openapi.models.metric_value.MetricValue(
                                key = '', 
                                value = 1.337, )
                            ], 
                        outcome = '', 
                        score = 1.337, 
                        skip = '', 
                        tenant_id = '', )
                    ],
                tenant_id = '',
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_by = ''
            )
        else:
            return Call(
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_by = '',
                duration_ms = 56,
                guardrail_id = '',
                id = '',
                metadata = None,
                outcome = 'pass',
                payload = modelmetry.openapi.models.payload.Payload(
                    input = modelmetry.openapi.models.input.Input(
                        chat = modelmetry.openapi.models.chat_input.ChatInput(
                            messages = [
                                modelmetry.openapi.models.simple_message.SimpleMessage(
                                    contents = [
                                        modelmetry.openapi.models.simple_part.SimplePart(
                                            detail = 'auto', 
                                            mime_type = '', 
                                            text = '', 
                                            uri = '', )
                                        ], 
                                    name = '', 
                                    role = 'system', 
                                    tool_call_id = '', 
                                    tool_calls = [
                                        modelmetry.openapi.models.tool_call.ToolCall(
                                            function = modelmetry.openapi.models.function.Function(
                                                arguments = null, 
                                                name = '', ), 
                                            id = '', 
                                            type = 'function', )
                                        ], )
                                ], 
                            settings = modelmetry.openapi.models.simple_options.SimpleOptions(
                                frequency_penalty = 1.337, 
                                logprobs = True, 
                                max_tokens = 56, 
                                n = 56, 
                                presence_penalty = 1.337, 
                                seed = 56, 
                                stream = True, 
                                temperature = 0, 
                                timeout = 0, 
                                tool_choice = '', 
                                tools = [
                                    modelmetry.openapi.models.tool.Tool(
                                        description = '', 
                                        name = '', 
                                        parameters = null, )
                                    ], 
                                top_logprobs = 56, 
                                top_p = 0, 
                                user = '', ), ), 
                        text = modelmetry.openapi.models.text_input.TextInput(
                            text = '', ), ), 
                    output = modelmetry.openapi.models.output.Output(), ),
                summarised_entries = [
                    modelmetry.openapi.models.summarised_entry.SummarisedEntry(
                        duration_ms = 56, 
                        evaluator_id = '', 
                        id = '', 
                        instance_id = '', 
                        message = '', 
                        metrics = [
                            modelmetry.openapi.models.metric_value.MetricValue(
                                key = '', 
                                value = 1.337, )
                            ], 
                        outcome = '', 
                        score = 1.337, 
                        skip = '', 
                        tenant_id = '', )
                    ],
                tenant_id = '',
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_by = '',
        )
        """

    def testCall(self):
        """Test Call"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
