# coding: utf-8

"""
    Modelmetry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from modelmetry.openapi.models.evaluate_request_by_instance import EvaluateRequestByInstance

class TestEvaluateRequestByInstance(unittest.TestCase):
    """EvaluateRequestByInstance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EvaluateRequestByInstance:
        """Test EvaluateRequestByInstance
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EvaluateRequestByInstance`
        """
        model = EvaluateRequestByInstance()
        if include_optional:
            return EvaluateRequestByInstance(
                instance_id = '',
                payload = modelmetry.openapi.models.payload.Payload(
                    completion = {
                        'key' : null
                        }, )
            )
        else:
            return EvaluateRequestByInstance(
                instance_id = '',
                payload = modelmetry.openapi.models.payload.Payload(
                    completion = {
                        'key' : null
                        }, ),
        )
        """

    def testEvaluateRequestByInstance(self):
        """Test EvaluateRequestByInstance"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
