# coding: utf-8

"""
    Modelmetry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from modelmetry.openapi.models.create_finding_params import CreateFindingParams

class TestCreateFindingParams(unittest.TestCase):
    """CreateFindingParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateFindingParams:
        """Test CreateFindingParams
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateFindingParams`
        """
        model = CreateFindingParams()
        if include_optional:
            return CreateFindingParams(
                at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                comment = '',
                description = '',
                entry_id = '',
                metadata = None,
                name = '',
                source = 'annotation',
                span_id = '',
                trace_id = '',
                value = None,
                xid = ''
            )
        else:
            return CreateFindingParams(
                name = '',
                value = None,
                xid = '',
        )
        """

    def testCreateFindingParams(self):
        """Test CreateFindingParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
