# coding: utf-8

"""
    Modelmetry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from modelmetry.openapi.models.modelmetry_score_llmas_judge_v1_config import ModelmetryScoreLLMAsJudgeV1Config

class TestModelmetryScoreLLMAsJudgeV1Config(unittest.TestCase):
    """ModelmetryScoreLLMAsJudgeV1Config unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelmetryScoreLLMAsJudgeV1Config:
        """Test ModelmetryScoreLLMAsJudgeV1Config
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelmetryScoreLLMAsJudgeV1Config`
        """
        model = ModelmetryScoreLLMAsJudgeV1Config()
        if include_optional:
            return ModelmetryScoreLLMAsJudgeV1Config(
                finding_name = '',
                instructions = '0',
                max_tokens = 56,
                model = 'openai/gpt-4o-mini'
            )
        else:
            return ModelmetryScoreLLMAsJudgeV1Config(
                finding_name = '',
                instructions = '0',
                max_tokens = 56,
                model = 'openai/gpt-4o-mini',
        )
        """

    def testModelmetryScoreLLMAsJudgeV1Config(self):
        """Test ModelmetryScoreLLMAsJudgeV1Config"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
