# coding: utf-8

"""
    Modelmetry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from modelmetry.openapi.models.full_trace import FullTrace

class TestFullTrace(unittest.TestCase):
    """FullTrace unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FullTrace:
        """Test FullTrace
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FullTrace`
        """
        model = FullTrace()
        if include_optional:
            return FullTrace(
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                end = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                events = [
                    {
                        'key' : null
                        }
                    ],
                findings = [
                    {
                        'key' : null
                        }
                    ],
                id = '',
                metadata = {
                    'key' : null
                    },
                name = '',
                session_id = '',
                spans = [
                    {
                        'key' : null
                        }
                    ],
                start = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                tenant_id = '',
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                xid = ''
            )
        else:
            return FullTrace(
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                end = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                events = [
                    {
                        'key' : null
                        }
                    ],
                findings = [
                    {
                        'key' : null
                        }
                    ],
                id = '',
                metadata = {
                    'key' : null
                    },
                name = '',
                spans = [
                    {
                        'key' : null
                        }
                    ],
                start = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                tenant_id = '',
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                xid = '',
        )
        """

    def testFullTrace(self):
        """Test FullTrace"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
