# coding: utf-8

"""
    Modelmetry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from modelmetry.openapi.models.modelmetry_tools_called_v1_expectation import ModelmetryToolsCalledV1Expectation

class TestModelmetryToolsCalledV1Expectation(unittest.TestCase):
    """ModelmetryToolsCalledV1Expectation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelmetryToolsCalledV1Expectation:
        """Test ModelmetryToolsCalledV1Expectation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelmetryToolsCalledV1Expectation`
        """
        model = ModelmetryToolsCalledV1Expectation()
        if include_optional:
            return ModelmetryToolsCalledV1Expectation(
                expression = '',
                name = ''
            )
        else:
            return ModelmetryToolsCalledV1Expectation(
                expression = '',
                name = '',
        )
        """

    def testModelmetryToolsCalledV1Expectation(self):
        """Test ModelmetryToolsCalledV1Expectation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
