# coding: utf-8

"""
    Modelmetry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from modelmetry.openapi.models.evaluate_request_body import EvaluateRequestBody

class TestEvaluateRequestBody(unittest.TestCase):
    """EvaluateRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EvaluateRequestBody:
        """Test EvaluateRequestBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EvaluateRequestBody`
        """
        model = EvaluateRequestBody()
        if include_optional:
            return EvaluateRequestBody(
                var_schema = '',
                by_config = {
                    'key' : null
                    },
                by_entry = modelmetry.openapi.models.evaluate_request_by_entry.EvaluateRequestByEntry(
                    entry_id = '', ),
                by_instance = modelmetry.openapi.models.evaluate_request_by_instance.EvaluateRequestByInstance(
                    instance_id = '', 
                    payload = modelmetry.openapi.models.payload.Payload(
                        completion = {
                            'key' : null
                            }, ), ),
                persist = True,
                tenant_id = ''
            )
        else:
            return EvaluateRequestBody(
                tenant_id = '',
        )
        """

    def testEvaluateRequestBody(self):
        """Test EvaluateRequestBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
