# coding: utf-8

"""
    Modelmetry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from modelmetry.openapi.models.finding import Finding

class TestFinding(unittest.TestCase):
    """Finding unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Finding:
        """Test Finding
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Finding`
        """
        model = Finding()
        if include_optional:
            return Finding(
                check_id = '',
                comment = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                entry_id = '',
                evaluator_id = '',
                id = '',
                metadata = None,
                name = '',
                source = 'annotation',
                span_id = '',
                tenant_id = '',
                trace_id = '',
                unit = '',
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                value = None,
                xid = ''
            )
        else:
            return Finding(
                comment = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                evaluator_id = '',
                id = '',
                metadata = None,
                name = '',
                source = 'annotation',
                tenant_id = '',
                unit = '',
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                value = None,
                xid = '',
        )
        """

    def testFinding(self):
        """Test Finding"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
