# coding: utf-8

"""
    Modelmetry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from modelmetry.openapi.models.span import Span

class TestSpan(unittest.TestCase):
    """Span unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Span:
        """Test Span
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Span`
        """
        model = Span()
        if include_optional:
            return Span(
                attributes = None,
                completion = modelmetry.openapi.models.completion_payload.CompletionPayload(
                    context = modelmetry.openapi.models.completion_payload_context.CompletionPayloadContext(
                        parsed_system = '', 
                        retrieved_items = [
                            {
                                'key' : null
                                }
                            ], ), 
                    input = modelmetry.openapi.models.input.Input(
                        chat = modelmetry.openapi.models.chat_input.ChatInput(
                            messages = [
                                modelmetry.openapi.models.simple_message.SimpleMessage(
                                    contents = [
                                        modelmetry.openapi.models.simple_part.SimplePart(
                                            detail = 'auto', 
                                            mime_type = '', 
                                            text = '', 
                                            uri = '', )
                                        ], 
                                    name = '', 
                                    role = 'system', 
                                    tool_call_id = '', 
                                    tool_calls = [
                                        modelmetry.openapi.models.tool_call.ToolCall(
                                            function = modelmetry.openapi.models.function.Function(
                                                arguments = null, 
                                                name = '', ), 
                                            id = '', 
                                            type = 'function', )
                                        ], )
                                ], 
                            settings = modelmetry.openapi.models.simple_options.SimpleOptions(
                                frequency_penalty = 1.337, 
                                logprobs = True, 
                                max_tokens = 56, 
                                n = 56, 
                                presence_penalty = 1.337, 
                                seed = 56, 
                                stream = True, 
                                temperature = 0, 
                                timeout = 0, 
                                tool_choice = '', 
                                tools = [
                                    modelmetry.openapi.models.tool.Tool(
                                        description = '', 
                                        name = '', 
                                        parameters = null, )
                                    ], 
                                top_logprobs = 56, 
                                top_p = 0, 
                                user = '', ), ), 
                        text = modelmetry.openapi.models.text_input.TextInput(
                            text = '', ), ), 
                    model = '', 
                    options = modelmetry.openapi.models.simple_options.SimpleOptions(
                        frequency_penalty = 1.337, 
                        logprobs = True, 
                        max_tokens = 56, 
                        n = 56, 
                        presence_penalty = 1.337, 
                        seed = 56, 
                        stream = True, 
                        temperature = 0, 
                        timeout = 0, 
                        tool_choice = '', 
                        top_logprobs = 56, 
                        top_p = 0, 
                        user = '', ), 
                    output = modelmetry.openapi.models.output.Output(), ),
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                embeddings = modelmetry.openapi.models.embeddings_payload.EmbeddingsPayload(
                    inputs = [
                        ''
                        ], 
                    options = modelmetry.openapi.models.simple_options.SimpleOptions(
                        frequency_penalty = 1.337, 
                        logprobs = True, 
                        max_tokens = 56, 
                        n = 56, 
                        presence_penalty = 1.337, 
                        seed = 56, 
                        stream = True, 
                        temperature = 0, 
                        timeout = 0, 
                        tool_choice = '', 
                        tools = [
                            modelmetry.openapi.models.tool.Tool(
                                description = '', 
                                name = '', 
                                parameters = null, )
                            ], 
                        top_logprobs = 56, 
                        top_p = 0, 
                        user = '', ), ),
                end = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                events = [
                    {
                        'key' : null
                        }
                    ],
                family = '',
                findings = [
                    {
                        'key' : null
                        }
                    ],
                id = '',
                message = '',
                name = '',
                other = None,
                parent_id = '',
                retrieval = modelmetry.openapi.models.retrieval_payload.RetrievalPayload(
                    queries = [
                        modelmetry.openapi.models.retrieval_query.RetrievalQuery(
                            embeddings = [
                                1.337
                                ], 
                            name = '', )
                        ], 
                    retrieved = [
                        {
                            'key' : null
                            }
                        ], ),
                severity = '',
                start = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                tenant_id = '',
                trace_id = '',
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                xid = ''
            )
        else:
            return Span(
                attributes = None,
                completion = modelmetry.openapi.models.completion_payload.CompletionPayload(
                    context = modelmetry.openapi.models.completion_payload_context.CompletionPayloadContext(
                        parsed_system = '', 
                        retrieved_items = [
                            {
                                'key' : null
                                }
                            ], ), 
                    input = modelmetry.openapi.models.input.Input(
                        chat = modelmetry.openapi.models.chat_input.ChatInput(
                            messages = [
                                modelmetry.openapi.models.simple_message.SimpleMessage(
                                    contents = [
                                        modelmetry.openapi.models.simple_part.SimplePart(
                                            detail = 'auto', 
                                            mime_type = '', 
                                            text = '', 
                                            uri = '', )
                                        ], 
                                    name = '', 
                                    role = 'system', 
                                    tool_call_id = '', 
                                    tool_calls = [
                                        modelmetry.openapi.models.tool_call.ToolCall(
                                            function = modelmetry.openapi.models.function.Function(
                                                arguments = null, 
                                                name = '', ), 
                                            id = '', 
                                            type = 'function', )
                                        ], )
                                ], 
                            settings = modelmetry.openapi.models.simple_options.SimpleOptions(
                                frequency_penalty = 1.337, 
                                logprobs = True, 
                                max_tokens = 56, 
                                n = 56, 
                                presence_penalty = 1.337, 
                                seed = 56, 
                                stream = True, 
                                temperature = 0, 
                                timeout = 0, 
                                tool_choice = '', 
                                tools = [
                                    modelmetry.openapi.models.tool.Tool(
                                        description = '', 
                                        name = '', 
                                        parameters = null, )
                                    ], 
                                top_logprobs = 56, 
                                top_p = 0, 
                                user = '', ), ), 
                        text = modelmetry.openapi.models.text_input.TextInput(
                            text = '', ), ), 
                    model = '', 
                    options = modelmetry.openapi.models.simple_options.SimpleOptions(
                        frequency_penalty = 1.337, 
                        logprobs = True, 
                        max_tokens = 56, 
                        n = 56, 
                        presence_penalty = 1.337, 
                        seed = 56, 
                        stream = True, 
                        temperature = 0, 
                        timeout = 0, 
                        tool_choice = '', 
                        top_logprobs = 56, 
                        top_p = 0, 
                        user = '', ), 
                    output = modelmetry.openapi.models.output.Output(), ),
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                embeddings = modelmetry.openapi.models.embeddings_payload.EmbeddingsPayload(
                    inputs = [
                        ''
                        ], 
                    options = modelmetry.openapi.models.simple_options.SimpleOptions(
                        frequency_penalty = 1.337, 
                        logprobs = True, 
                        max_tokens = 56, 
                        n = 56, 
                        presence_penalty = 1.337, 
                        seed = 56, 
                        stream = True, 
                        temperature = 0, 
                        timeout = 0, 
                        tool_choice = '', 
                        tools = [
                            modelmetry.openapi.models.tool.Tool(
                                description = '', 
                                name = '', 
                                parameters = null, )
                            ], 
                        top_logprobs = 56, 
                        top_p = 0, 
                        user = '', ), ),
                end = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                events = [
                    {
                        'key' : null
                        }
                    ],
                family = '',
                findings = [
                    {
                        'key' : null
                        }
                    ],
                id = '',
                message = '',
                name = '',
                other = None,
                parent_id = '',
                retrieval = modelmetry.openapi.models.retrieval_payload.RetrievalPayload(
                    queries = [
                        modelmetry.openapi.models.retrieval_query.RetrievalQuery(
                            embeddings = [
                                1.337
                                ], 
                            name = '', )
                        ], 
                    retrieved = [
                        {
                            'key' : null
                            }
                        ], ),
                severity = '',
                start = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                tenant_id = '',
                trace_id = '',
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                xid = '',
        )
        """

    def testSpan(self):
        """Test Span"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
