# coding: utf-8

"""
    Modelmetry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from modelmetry.openapi.models.modelmetry_secret_detector_v1_config import ModelmetrySecretDetectorV1Config

class TestModelmetrySecretDetectorV1Config(unittest.TestCase):
    """ModelmetrySecretDetectorV1Config unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelmetrySecretDetectorV1Config:
        """Test ModelmetrySecretDetectorV1Config
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelmetrySecretDetectorV1Config`
        """
        model = ModelmetrySecretDetectorV1Config()
        if include_optional:
            return ModelmetrySecretDetectorV1Config(
                custom_patterns = {
                    'key' : ''
                    }
            )
        else:
            return ModelmetrySecretDetectorV1Config(
        )
        """

    def testModelmetrySecretDetectorV1Config(self):
        """Test ModelmetrySecretDetectorV1Config"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
