# coding: utf-8

"""
    Modelmetry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from modelmetry.openapi.models.modelmetry_json_validator_v1_config import ModelmetryJSONValidatorV1Config

class TestModelmetryJSONValidatorV1Config(unittest.TestCase):
    """ModelmetryJSONValidatorV1Config unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelmetryJSONValidatorV1Config:
        """Test ModelmetryJSONValidatorV1Config
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelmetryJSONValidatorV1Config`
        """
        model = ModelmetryJSONValidatorV1Config()
        if include_optional:
            return ModelmetryJSONValidatorV1Config(
                expected_json_schema = ''
            )
        else:
            return ModelmetryJSONValidatorV1Config(
        )
        """

    def testModelmetryJSONValidatorV1Config(self):
        """Test ModelmetryJSONValidatorV1Config"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
