# coding: utf-8

"""
    Modelmetry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from modelmetry.openapi.models.retrieved_item import RetrievedItem

class TestRetrievedItem(unittest.TestCase):
    """RetrievedItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RetrievedItem:
        """Test RetrievedItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RetrievedItem`
        """
        model = RetrievedItem()
        if include_optional:
            return RetrievedItem(
                content = None,
                content_type = '',
                identifier = '',
                metadata = None
            )
        else:
            return RetrievedItem(
                content = None,
                content_type = '',
                identifier = '',
                metadata = None,
        )
        """

    def testRetrievedItem(self):
        """Test RetrievedItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
