# coding: utf-8

"""
    Modelmetry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from modelmetry.openapi.models.modelmetry_text_readability_v1_config import ModelmetryTextReadabilityV1Config

class TestModelmetryTextReadabilityV1Config(unittest.TestCase):
    """ModelmetryTextReadabilityV1Config unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelmetryTextReadabilityV1Config:
        """Test ModelmetryTextReadabilityV1Config
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelmetryTextReadabilityV1Config`
        """
        model = ModelmetryTextReadabilityV1Config()
        if include_optional:
            return ModelmetryTextReadabilityV1Config(
                scope = 'last'
            )
        else:
            return ModelmetryTextReadabilityV1Config(
                scope = 'last',
        )
        """

    def testModelmetryTextReadabilityV1Config(self):
        """Test ModelmetryTextReadabilityV1Config"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
