# coding: utf-8

"""
    Modelmetry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from modelmetry.openapi.models.completion_payload_input import CompletionPayloadInput

class TestCompletionPayloadInput(unittest.TestCase):
    """CompletionPayloadInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CompletionPayloadInput:
        """Test CompletionPayloadInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CompletionPayloadInput`
        """
        model = CompletionPayloadInput()
        if include_optional:
            return CompletionPayloadInput(
                text = '',
                messages = [
                    modelmetry.openapi.models.chat_input_messages_inner.ChatInput_Messages_inner()
                    ],
                options = {
                    'key' : null
                    }
            )
        else:
            return CompletionPayloadInput(
                text = '',
                options = {
                    'key' : null
                    },
        )
        """

    def testCompletionPayloadInput(self):
        """Test CompletionPayloadInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
