# coding: utf-8

"""
    Modelmetry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from modelmetry.openapi.models.modelmetry_sentiment_analysis_v1_config import ModelmetrySentimentAnalysisV1Config

class TestModelmetrySentimentAnalysisV1Config(unittest.TestCase):
    """ModelmetrySentimentAnalysisV1Config unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelmetrySentimentAnalysisV1Config:
        """Test ModelmetrySentimentAnalysisV1Config
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelmetrySentimentAnalysisV1Config`
        """
        model = ModelmetrySentimentAnalysisV1Config()
        if include_optional:
            return ModelmetrySentimentAnalysisV1Config(
                model = 'openai/gpt-4o-mini',
                scope = 'interaction.last'
            )
        else:
            return ModelmetrySentimentAnalysisV1Config(
                model = 'openai/gpt-4o-mini',
                scope = 'interaction.last',
        )
        """

    def testModelmetrySentimentAnalysisV1Config(self):
        """Test ModelmetrySentimentAnalysisV1Config"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
