# coding: utf-8

"""
    Modelmetry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from modelmetry.openapi.models.completion_family_data_input import CompletionFamilyDataInput
from modelmetry.openapi.models.cost import Cost
from modelmetry.openapi.models.document import Document
from modelmetry.openapi.models.options import Options
from modelmetry.openapi.models.output import Output
from modelmetry.openapi.models.usage import Usage
from typing import Optional, Set
from typing_extensions import Self

class CompletionFamilyData(BaseModel):
    """
    CompletionFamilyData
    """ # noqa: E501
    cost: Optional[Cost] = Field(default=None, alias="Cost")
    documents: Optional[List[Document]] = Field(default=None, alias="Documents")
    input: Optional[CompletionFamilyDataInput] = Field(default=None, alias="Input")
    options: Optional[Options] = Field(default=None, alias="Options")
    output: Optional[Output] = Field(default=None, alias="Output")
    usage: Optional[Usage] = Field(default=None, alias="Usage")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["Cost", "Documents", "Input", "Options", "Output", "Usage"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CompletionFamilyData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of cost
        if self.cost:
            _dict['Cost'] = self.cost.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in documents (list)
        _items = []
        if self.documents:
            for _item in self.documents:
                if _item:
                    _items.append(_item.to_dict())
            _dict['Documents'] = _items
        # override the default output from pydantic by calling `to_dict()` of input
        if self.input:
            _dict['Input'] = self.input.to_dict()
        # override the default output from pydantic by calling `to_dict()` of options
        if self.options:
            _dict['Options'] = self.options.to_dict()
        # override the default output from pydantic by calling `to_dict()` of output
        if self.output:
            _dict['Output'] = self.output.to_dict()
        # override the default output from pydantic by calling `to_dict()` of usage
        if self.usage:
            _dict['Usage'] = self.usage.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CompletionFamilyData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Cost": Cost.from_dict(obj["Cost"]) if obj.get("Cost") is not None else None,
            "Documents": [Document.from_dict(_item) for _item in obj["Documents"]] if obj.get("Documents") is not None else None,
            "Input": CompletionFamilyDataInput.from_dict(obj["Input"]) if obj.get("Input") is not None else None,
            "Options": Options.from_dict(obj["Options"]) if obj.get("Options") is not None else None,
            "Output": Output.from_dict(obj["Output"]) if obj.get("Output") is not None else None,
            "Usage": Usage.from_dict(obj["Usage"]) if obj.get("Usage") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


