# coding: utf-8

"""
    Modelmetry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from modelmetry.openapi.models.grading_configuration import GradingConfiguration
from modelmetry.openapi.models.payload import Payload
from typing import Optional, Set
from typing_extensions import Self

class EvaluateRequestByConfig(BaseModel):
    """
    EvaluateRequestByConfig
    """ # noqa: E501
    config: Dict[str, Any] = Field(alias="Config")
    evaluator_id: StrictStr = Field(alias="EvaluatorID")
    grading: Optional[GradingConfiguration] = Field(default=None, alias="Grading")
    payload: Payload = Field(alias="Payload")
    secrets: Optional[List[StrictStr]] = Field(default=None, alias="Secrets")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["Config", "EvaluatorID", "Grading", "Payload", "Secrets"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EvaluateRequestByConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of grading
        if self.grading:
            _dict['Grading'] = self.grading.to_dict()
        # override the default output from pydantic by calling `to_dict()` of payload
        if self.payload:
            _dict['Payload'] = self.payload.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EvaluateRequestByConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Config": obj.get("Config"),
            "EvaluatorID": obj.get("EvaluatorID"),
            "Grading": GradingConfiguration.from_dict(obj["Grading"]) if obj.get("Grading") is not None else None,
            "Payload": Payload.from_dict(obj["Payload"]) if obj.get("Payload") is not None else None,
            "Secrets": obj.get("Secrets")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


