# coding: utf-8

"""
    Modelmetry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

class ModelmetrySentimentAnalysisV1Config(BaseModel):
    """
    ModelmetrySentimentAnalysisV1Config
    """ # noqa: E501
    model: StrictStr = Field(description="The model to use.", alias="Model")
    scope: StrictStr = Field(alias="Scope")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["Model", "Scope"]

    @field_validator('model')
    def model_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['openai/gpt-4o-mini', 'openai/gpt-4o', 'openai/gpt-3.5-turbo', 'groq/llama3-8b-8192', 'groq/llama3-70b-8192', 'groq/mixtral-8x7b-32768', 'groq/gemma-7b-it', 'google/gemini-1.5-flash', 'google/gemini-1.5-pro']):
            raise ValueError("must be one of enum values ('openai/gpt-4o-mini', 'openai/gpt-4o', 'openai/gpt-3.5-turbo', 'groq/llama3-8b-8192', 'groq/llama3-70b-8192', 'groq/mixtral-8x7b-32768', 'groq/gemma-7b-it', 'google/gemini-1.5-flash', 'google/gemini-1.5-pro')")
        return value

    @field_validator('scope')
    def scope_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['interaction.last', 'user.last', 'assistant.last', 'last']):
            raise ValueError("must be one of enum values ('interaction.last', 'user.last', 'assistant.last', 'last')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ModelmetrySentimentAnalysisV1Config from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ModelmetrySentimentAnalysisV1Config from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Model": obj.get("Model") if obj.get("Model") is not None else 'openai/gpt-4o-mini',
            "Scope": obj.get("Scope")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


