# coding: utf-8

"""
    Modelmetry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from modelmetry.openapi.models.completion_family_data_input import CompletionFamilyDataInput
from modelmetry.openapi.models.options import Options
from modelmetry.openapi.models.output import Output
from typing import Optional, Set
from typing_extensions import Self

class Payload(BaseModel):
    """
    Payload
    """ # noqa: E501
    input: Optional[CompletionFamilyDataInput] = Field(default=None, alias="Input")
    options: Optional[Options] = Field(default=None, alias="Options")
    output: Optional[Output] = Field(default=None, alias="Output")
    __properties: ClassVar[List[str]] = ["Input", "Options", "Output"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Payload from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of input
        if self.input:
            _dict['Input'] = self.input.to_dict()
        # override the default output from pydantic by calling `to_dict()` of options
        if self.options:
            _dict['Options'] = self.options.to_dict()
        # override the default output from pydantic by calling `to_dict()` of output
        if self.output:
            _dict['Output'] = self.output.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Payload from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Input": CompletionFamilyDataInput.from_dict(obj["Input"]) if obj.get("Input") is not None else None,
            "Options": Options.from_dict(obj["Options"]) if obj.get("Options") is not None else None,
            "Output": Output.from_dict(obj["Output"]) if obj.get("Output") is not None else None
        })
        return _obj


